---
# defaults file for docker_management
docker_compose_binary_path: "/usr/local/bin/docker-compose"
docker_compose_plugin_package: "docker-compose-plugin"
docker_ce_package: "docker-ce"
docker_compose_service_path: "/home/paul/docker/stacks/app1"

docker_src: "/home/paul/docker/"  # Default path to the Docker Compose file
docker_prerequisites:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

docker_software:
  - docker-ce
  - docker-ce-cli
  - containerd.io
